### ISSUE TITLE
distutils package is deprecated

### ISSUE THREAD

**Issue by InfamousPlatypus** [tbarnetlamb/hyphen#22]
It appears that the distutils package is deprecated error is no longer giving warnings, but returning a non-zero exit code (1) on Ubuntu 22.04.1 as such I cannot install. I'll see what I can do to give options shortly.

If you like here is the whole error.

``/home/user/hyphen/hyphen/build-extn.py:3: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import sys, distutils.sysconfig, os, os.path, subprocess, optparse
/home/user/hyphen/hyphen/build-extn.py:3: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
  import sys, distutils.sysconfig, os, os.path, subprocess, optparse
[ 2 of 12] Compiling HyphenKinds      ( /home/user/hyphen/hyphen/lowlevel_src/HyphenKinds.hs, /home/user/hyphen/hyphen/lowlevel_inter/HyphenKinds.o )

/home/user/hyphen/hyphen/lowlevel_src/HyphenKinds.hs:9:1: error:
    Could not find module ‘Data.Hashable’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
9 | import Data.Hashable
  | ^^^^^^^^^^^^^^^^^^^^
Traceback (most recent call last):
  File "/home/user/hyphen/hyphen/build-extn.py", line 130, in <module>
    subprocess.check_call(invocation + ['-no-link'])
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ghc', '-dynamic', '-shared', '-fPIC', '-no-hs-main', '-fwarn-unused-imports', '-cpp', '/home/user/hyphen/hyphen/lowlevel_src/Hyphen.hs', '/home/user/hyphen/hyphen/lowlevel_src/hyphen_c.c', '-i/home/user/hyphen/hyphen/lowlevel_src', '-hidir', '/home/user/hyphen/hyphen/lowlevel_inter', '-odir', '/home/user/hyphen/hyphen/lowlevel_inter', '-I/usr/include/python3.10', '-package', 'ghc', '-lHSrts_thr-ghc8.8.4\n', '-lpython3.10', '-no-link']' returned non-zero exit status 1.

**Comment by tbarnetlamb** [comment]
Thanks for the report!

Looking over the error message, I actually think that the deprecation of `distutils` is not the fatal error here. What's actually killing the build is an error message from `ghc`, the Haskell compiler, as invoked by `build-extn.py` in a subprocess.

In particular, the fatal error is:
```
/home/user/hyphen/hyphen/lowlevel_src/HyphenKinds.hs:9:1: error:
Could not find module ‘Data.Hashable’
```
which sounds like the problem is that `Data.Hashable` hasn't been installed (there are instructions in `BUILDING.MD`). But in any case, I guess it's better to discuss such issues in #23. The deprecation of `distutils` will cause a fatal error soon, and so the point you raise here is valid in its own right. I will keep this issue open and work to address the dependency on `distutils` shortly!
